name: 'order_analytics'
version: '1.0.0'
config-version: 2

# Profile name must match profiles.yml
profile: 'order_analytics'

# Paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  order_analytics:
    +materialized: table
    gold:
      +materialized: table
    silver:
      +materialized: view
    staging:
      +materialized: view